all:
	armcc -c uart.c -o uart.o
	armcc -c stdio.c -o stdio.o
	armcc -c main.c -o main.o
	armasm start.s -o start.o	
	armcc -c command.c -o command.o
	armcc -c myprintf.c -o myprintf.o
	armcc -c nandflash.c -o nandflash.o
	armlink -entry mymain -ro-base 0x0 -first start.o -o uart.axf uart.o start.o main.o stdio.o myprintf.o command.o nandflash.o
	fromelf -bin uart.axf -o nandflash.bin 
	fromelf -c uart.axf -o uart.txt
	dir *.bin

clean:
	del *.o
	